# Generated by Django 3.2 on 2021-04-22 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 14, 3, 15, 700086, tzinfo=utc)),
        ),
    ]
