# Generated by Django 3.2 on 2021-04-30 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ak_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 16, 18, 8, 962613, tzinfo=utc)),
        ),
    ]
